Fix compilation error: can't take address of temporary
The issue was trying to take the address of the return value from
getCurrentDescriptorSet(). Now we store it in a variable first before
passing its address to vkCmdBindDescriptorSets.

Fixes MSVC error C2102: '&' requires l-value